name: Build and Release RIS_app

on:
  push:
    branches: [main]
  tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install ruff pytest

      - name: Run lint
        run: ruff check .

      - name: Run tests
        run: pytest

      - name: Generate catalog
        run: python scripts/gen_catalog.py

      - name: Prepare artifacts directory
        run: |
          mkdir -p artifacts
          cp ris_app/data/catalog.json artifacts/catalog.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ris_app_build
          path: artifacts

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.zip
            artifacts/catalog.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
